name: wtw
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  image_picker: ^0.8.7+4
  provider: ^6.0.5
  geolocator: ^14.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^8.0.0
  openai_dart: ^0.1.0
  crypto: ^3.0.3
  flutter_image_compress: ^2.4.0
  uuid: ^4.3.3
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/images/
    - .env

  uses-material-design: true
